server:
  port: 8080
## test1 database
#spring.datasource.test1.url=jdbc:mysql://10.139.60.170:3306/vts-mos?useUnicode=true&amp&characterEncoding=utf-8&amp&serverTimezone=GMT%2B8&amp&useSSL=false
#spring.datasource.test1.username=mosuser
#spring.datasource.test1.password=1234567a
#spring.datasource.test1.driver-class-name=com.mysql.cj.jdbc.Driver
### test2 database
#spring.datasource.test2.url=jdbc:mysql://10.139.60.170:3306/mos-news?useUnicode=true&amp&characterEncoding=utf-8&amp&serverTimezone=GMT%2B8&amp&useSSL=false
#spring.datasource.test2.username=mosuser
#spring.datasource.test2.password=1234567a
#spring.datasource.test2.driver-class-name=com.mysql.cj.jdbc.Driver
customer-database:
  dataSources:
    test01:
       primary: true
       url: jdbc:mysql://10.139.60.170:3306/vts-mos?useUnicode=true&amp&characterEncoding=utf-8&amp&serverTimezone=GMT%2B8&amp&useSSL=false
       username: mosuser
       password: 1234567a
       driver-class-name: com.mysql.cj.jdbc.Driver
    test02:
       url: jdbc:mysql://10.139.60.170:3306/mos-news?useUnicode=true&amp&characterEncoding=utf-8&amp&serverTimezone=GMT%2B8&amp&useSSL=false
       username: mosuser
       password: 1234567a
       driver-class-name: com.mysql.cj.jdbc.Driver


logging:
  level:
    com.tj.mapper: debug
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#开启MyBatis的二级缓存
    cache-enabled: true



